---
title: Hafta 07
subtitle: "Yön. Araş. : Soru Çözümü 1"
date: 10/30/2025
date-format: DD/MM/YYYY
author: "Doç. Dr. Erhan Çene"
format: 
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: true
    preview-links: auto
    logo: images/iticulogo.png
    css: styles.css
    footer: "IST207 - Yöneylem Araştırması - Hafta 07 - 30 Ekim 2025 - Doç. Dr. Erhan Çene"
    # width: 2000
    # height: 1500
filters:
  - parse-latex
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
---

## Örnek 1: Ulaştırma Problemi - Min 1 (1)


::: {.callout-tip icon=false title="Örnek 1: Başlangıç" style="font-size: 100%;"}

::: columns

::: {.column width="66%"}


:::{.tblbox .tbl-fs-xl .w-100 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\00_baslangic_tablosu.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}
Başlangıç dağılımı verilen ve maliyeti minimum yapmak isteyen ulaştırma probleminin 

a) Dengeli olup olmadığını belirleyerek düzenlemeleri yapınız.


:::
:::
b) amaç fonksiyonunu, kısıtlarını ve koşullarını yazınız, 
c) kuzeybatı, satır, sütun, en düşük maliyet ve VAM yöntemleriyle çözünüz. Her yöntem için MODI uygulayınız.
:::


## Örnek 1: Ulaştırma Problemi - Min 1 (2)


::: {.callout-tip icon=false title="Örnek 1: Dengeli-Dengesiz" style="font-size: 100%;"}

::: columns

::: {.column width="66%"}


:::{.tblbox .tbl-fs-xl .w-100 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\30_colmin_step_001_preview.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}
Satır toplamı 28, sütun toplamı 31 olduğundan toplam 3 birimlik ve 0 maliyetli bir gölge satır eklenmelidir.
:::
:::
:::


## Örnek 1: Ulaştırma Problemi - Min 1 (3)

::: {.callout-tip icon=false title="Örnek 1: Amaç ve Kısıtlar" style="font-size: 90%;"}



::: columns

::: {.column width="49%"}

Amaç [en küçük toplam ulaştırma maliyetini]{.light-red} belirlemek olduğuna göre

[\begin{align*} 
Z_{enk} &= 45x_{11}+17x_{12}+21x_{13}+30x_{14} \\
        &+ 14x_{21}+18x_{22}+19x_{23}+31x_{24} \\
        &+ 0x_{31}+0x_{32}+0x_{33}+0x_{34}
\end{align*}]{.light-blue}



[sunum kısıtları]{.light-red}

[$$
\begin{alignedat}{7}
x_{11} &+& x_{12}  &+& x_{13} &+& x_{14}  &\;= & 15\\
x_{21} &+& x_{22}  &+& x_{23} &+& x_{24}  &\;= & 13\\
x_{31} &+& x_{32}  &+& x_{33} &+& x_{34}  &\;= & 3
\end{alignedat}
$$]{.light-blue}

:::


::: {.column width="1%"}
:::

::: {.column width="49%"}

Diğer taraftan her satış deposunun ürün gereksiniminin tam olarak karşılanması istendiğinden [istem kısıtlayıcıları]{.light-red}


[$$
\begin{alignedat}{7}
x_{11} &+& x_{21}  &+& x_{31} &\;= & 9\\
x_{12} &+& x_{22}  &+& x_{32} &\;= & 6\\
x_{13} &+& x_{23}  &+& x_{33} &\;= & 7\\
x_{14} &+& x_{24}  &+& x_{34} &\;= & 9
\end{alignedat}
$$]{.light-blue}
:::

:::
[İşaret kısıtlaması:]{.light-red}
Son olarak negatif taşıma olmayacağına göre 
[$$x_{ij} \geq 0; \quad{} i = 1,2 \dots 3; \quad{} j = 1,2 \dots 4;$$]{.light-blue}
:::


## Örnek 1: Ulaştırma Problemi - Min 1 (4)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\30_northwest_step_001_preview.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (5)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\10_northwest_initial.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (6)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_001_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (7)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (8)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_northwest_it_001_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (9)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_northwest_it_001_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (10)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_002_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (11)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_002_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (12)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Geçiş Öncesi Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_northwest_it_002_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (13)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Geçiş Sonrası Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_northwest_it_002_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (14)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi uv Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_003_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (15)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi R Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_003_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (16)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Geçiş Öncesi Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_northwest_it_003_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (17)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Geçiş Sonrası Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_northwest_it_003_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (18)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi uv Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_004_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (19)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi R Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_northwest_step_004_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (20)

::: {.callout-tip icon=false title="Örnek 1: Kuzeybatı + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\20_northwest_modi.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (21)

::: {.callout-tip icon=false title="Örnek 1: Satır Min Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\30_rowmin_step_001_preview.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (22)

::: {.callout-tip icon=false title="Örnek 1: Satır Min Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\10_rowmin_initial.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (23)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_rowmin_step_001_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (24)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_rowmin_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (25)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_rowmin_it_001_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (26)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_rowmin_it_001_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (27)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_rowmin_step_002_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (28)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_rowmin_step_002_uvR_table.html >}}
```
:::

:::



## Örnek 1: Ulaştırma Problemi - Min 1 (29)

::: {.callout-tip icon=false title="Örnek 1: Satır min + Modi Geçiş Sonrası Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\20_rowmin_modi.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (30)

::: {.callout-tip icon=false title="Örnek 1: Sütun Min Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\30_colmin_step_001_preview.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (31)

::: {.callout-tip icon=false title="Örnek 1: Sütun Min Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\10_colmin_initial.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (32)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_colmin_step_001_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (33)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_colmin_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (34)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_colmin_it_001_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (35)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_colmin_it_001_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (36)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_colmin_step_002_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (37)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_colmin_step_002_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (38)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi Geçiş Öncesi Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_colmin_it_002_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (39)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi Geçiş Sonrası Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_colmin_it_002_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (40)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi uv Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_colmin_step_003_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (41)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi R Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_colmin_step_003_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (42)

::: {.callout-tip icon=false title="Örnek 1: Sütun min + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\20_colmin_modi.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (43)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\30_leastcost_step_001_preview.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (44)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\10_leastcost_initial.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (45)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_leastcost_step_001_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (46)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_leastcost_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (47)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_leastcost_it_001_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (48)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_leastcost_it_001_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (49)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_leastcost_step_002_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (50)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_leastcost_step_002_uvR_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (51)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi Geçiş Öncesi Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_leastcost_it_002_transition.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (52)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi Geçiş Sonrası Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\46_leastcost_it_002_transition_after.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (53)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi uv Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_leastcost_step_003_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 3 (54)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_leastcost_step_003_uvR_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (55)

::: {.callout-tip icon=false title="Örnek 1: En Düşük Maliyet + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\20_leastcost_modi.html >}}
```
:::

:::



## Örnek 1: Ulaştırma Problemi - Min 1 (56)

::: {.callout-tip icon=false title="Örnek 1: VAM Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\30_vam_step_001_preview.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (57)

::: {.callout-tip icon=false title="Örnek 1: VAM Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\10_vam_initial.html >}}
```
:::

:::


## Örnek 1: Ulaştırma Problemi - Min 1 (58)

::: {.callout-tip icon=false title="Örnek 1: VAM + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_vam_step_001_uv_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (59)

::: {.callout-tip icon=false title="Örnek 1: VAM + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\50_vam_step_001_uvR_table.html >}}
```
:::

:::

## Örnek 1: Ulaştırma Problemi - Min 1 (60)

::: {.callout-tip icon=false title="Örnek 1: VAM + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1\20_vam_modi.html >}}
```
:::

:::



## Örnek 2: Ulaştırma Problemi - Min 2 (1)


::: {.callout-tip icon=false title="Örnek 2: Başlangıç" style="font-size: 100%;"}

::: columns

::: {.column width="66%"}


:::{.tblbox .tbl-fs-xl .w-100 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\00_baslangic_tablosu.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}
Başlangıç dağılımı verilen ve maliyeti minimum yapmak isteyen ulaştırma probleminin 

a) Dengeli olup olmadığını belirleyerek düzenlemeleri yapınız.


:::
:::
b) amaç fonksiyonunu, kısıtlarını ve koşullarını yazınız, 
c) kuzeybatı, satır, sütun, en düşük maliyet ve VAM yöntemleriyle çözünüz. Her yöntem için MODI uygulayınız.
:::


## Örnek 2: Ulaştırma Problemi - Min 2 (2)


::: {.callout-tip icon=false title="Örnek 2: Dengeli-Dengesiz" style="font-size: 100%;"}

::: columns

::: {.column width="66%"}


:::{.tblbox .tbl-fs-xl .w-100 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\30_colmin_step_001_preview.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}
Satır toplamı 850, sütun toplamı 800 olduğundan toplam 50 birimlik ve 0 maliyetli bir gölge sütun eklenmelidir.
:::
:::
:::


## Örnek 2: Ulaştırma Problemi - Min 2 (3)

::: {.callout-tip icon=false title="Örnek 2: Amaç ve Kısıtlar" style="font-size: 90%;"}



::: columns

::: {.column width="49%"}

Amaç [en küçük toplam ulaştırma maliyetini]{.light-red} belirlemek olduğuna göre

[\begin{align*} 
Z_{enk} &= 10x_{11}+6x_{12}+5x_{13}+0x_{14} \\
        &+ 7x_{21}+8x_{22}+8x_{23}+0x_{24} \\
        &+ 6x_{31}+9x_{32}+12x_{33}+0x_{34}
\end{align*}]{.light-blue}



[sunum kısıtları]{.light-red}

[$$
\begin{alignedat}{7}
x_{11} &+& x_{12}  &+& x_{13} &+& x_{14}  &\;= & 200\\
x_{21} &+& x_{22}  &+& x_{23} &+& x_{24}  &\;= & 400\\
x_{31} &+& x_{32}  &+& x_{33} &+& x_{34}  &\;= & 250
\end{alignedat}
$$]{.light-blue}

:::


::: {.column width="1%"}
:::

::: {.column width="49%"}

Diğer taraftan her satış deposunun ürün gereksiniminin tam olarak karşılanması istendiğinden [istem kısıtlayıcıları]{.light-red}


[$$
\begin{alignedat}{7}
x_{11} &+& x_{21}  &+& x_{31} &\;= & 250\\
x_{12} &+& x_{22}  &+& x_{32} &\;= & 200\\
x_{13} &+& x_{23}  &+& x_{33} &\;= & 350\\
x_{14} &+& x_{24}  &+& x_{34} &\;= & 50
\end{alignedat}
$$]{.light-blue}
:::

:::
[İşaret kısıtlaması:]{.light-red}
Son olarak negatif taşıma olmayacağına göre 
[$$x_{ij} \geq 0; \quad{} i = 1,2 \dots 3; \quad{} j = 1,2 \dots 4;$$]{.light-blue}
:::


## Örnek 2: Ulaştırma Problemi - Min 2 (4)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\30_northwest_step_001_preview.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (5)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\10_northwest_initial.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (6)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_001_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (7)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (8)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_001_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (9)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_001_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (10)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_002_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (11)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_002_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (12)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Öncesi Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_002_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (13)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Sonrası Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_002_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (14)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi uv Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_003_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (15)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi R Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_003_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (16)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Öncesi Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_003_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (17)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Sonrası Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_003_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (18)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi uv Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_004_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (19)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi R Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_004_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (20)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Öncesi Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_004_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (21)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Geçiş Sonrası Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_northwest_it_004_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (22)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi uv Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_005_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (23)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi R Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_northwest_step_005_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (24)

::: {.callout-tip icon=false title="Örnek 2: Kuzeybatı + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\20_northwest_modi.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (25)

::: {.callout-tip icon=false title="Örnek 2: Satır Min Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\30_rowmin_step_001_preview.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (26)

::: {.callout-tip icon=false title="Örnek 2: Satır Min Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\10_rowmin_initial.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (27)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_001_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (28)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (29)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_001_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (30)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_001_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (31)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_002_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (32)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_002_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (33)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Öncesi Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_002_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (34)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Sonrası Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_002_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (35)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi uv Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_003_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (36)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi R Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_003_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (37)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Öncesi Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_003_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (38)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Sonrası Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_003_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (39)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi uv Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_004_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (40)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi R Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_004_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (41)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Öncesi Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_004_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (42)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Sonrası Adım 4" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_004_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (43)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi uv Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_005_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (44)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi R Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_005_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (45)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Öncesi Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_005_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (46)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Sonrası Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_rowmin_it_005_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (47)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi uv Adım 6" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_006_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (48)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi R Adım 6" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_rowmin_step_006_uvR_table.html >}}
```
:::

:::



## Örnek 2: Ulaştırma Problemi - Min 2 (49)

::: {.callout-tip icon=false title="Örnek 2: Satır min + Modi Geçiş Sonrası Adım 5" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\20_rowmin_modi.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (50)

::: {.callout-tip icon=false title="Örnek 2: Sütun Min Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\30_colmin_step_001_preview.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (51)

::: {.callout-tip icon=false title="Örnek 2: Sütun Min Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\10_colmin_initial.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (52)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_colmin_step_001_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (53)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_colmin_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (54)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_colmin_it_001_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (55)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_colmin_it_001_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (56)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_colmin_step_002_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (57)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_colmin_step_002_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (58)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi Geçiş Öncesi Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_colmin_it_002_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (59)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi Geçiş Sonrası Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_colmin_it_002_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (60)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi uv Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_colmin_step_003_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (61)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi R Adım 3" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_colmin_step_003_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (62)

::: {.callout-tip icon=false title="Örnek 2: Sütun min + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\20_colmin_modi.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (63)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\30_leastcost_step_001_preview.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (64)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\10_leastcost_initial.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (65)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_leastcost_step_001_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (66)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_leastcost_step_001_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (67)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi Geçiş Öncesi Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_leastcost_it_001_transition.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (68)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi Geçiş Sonrası Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\46_leastcost_it_001_transition_after.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (69)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi uv Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_leastcost_step_002_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (70)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi R Adım 2" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_leastcost_step_002_uvR_table.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (71)

::: {.callout-tip icon=false title="Örnek 2: En Düşük Maliyet + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\20_leastcost_modi.html >}}
```
:::

:::



## Örnek 2: Ulaştırma Problemi - Min 2 (72)

::: {.callout-tip icon=false title="Örnek 2: VAM Başlangıç" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\30_vam_step_001_preview.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (73)

::: {.callout-tip icon=false title="Örnek 2: VAM Başlangıç Çözümü" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\10_vam_initial.html >}}
```
:::

:::


## Örnek 2: Ulaştırma Problemi - Min 2 (74)

::: {.callout-tip icon=false title="Örnek 2: VAM + Modi uv Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_vam_step_001_uv_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (75)

::: {.callout-tip icon=false title="Örnek 2: VAM + Modi R Adım 1" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\50_vam_step_001_uvR_table.html >}}
```
:::

:::

## Örnek 2: Ulaştırma Problemi - Min 2 (76)

::: {.callout-tip icon=false title="Örnek 2: VAM + Modi Optimum Değer" style="font-size: 120%;"}

:::{.tblbox .tbl-fs-md .w-90 .scale-120  .pad-tight .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example2\20_vam_modi.html >}}
```
:::

:::

## Örnek 3: İş - Tezgah Eşleştirme (1)


::: {.callout-tip icon=false title="Soru" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}


:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_00_initial.html >}}
```
:::
İşlerin süreleri dakika olarak yukarıda verilmiştir. 

İşlerin [minimum sürede]{.light-red} yapılabilmesi için [hangi iş hangi tezgaha]{.light-red} yüklenmelidir.
:::
::: {.column width="3%"}
:::

::: {.column width="30%"}

Bir tekstil dokuma fabrikasında [dört]{.light-blue} [iş]{.light-red} [dört]{.light-blue} [tezgaha]{.light-red} yüklenecektir. 

Her iş bu tezgahların her birinde yapılacaktır. Her iş sadece bir tezgaha atanacak ve her tezgahta yalnızca bir iş yapılacaktır. 





:::

:::


:::





## Örnek 3: İş - Tezgah Eşleştirme (2)

::: {.callout-tip icon=false title="Amaç Fonksiyonu" style="font-size: 120%;"}

[Sürenin en az olması]{.light-red} istendiğinden [amaç fonksiyonu]{.red} aşağıdaki gibi yazılır.


[\begin{align*} 
Z_{enk} &= 21x_{11}+24x_{12}+26x_{13}+22x_{14} \\
        &+ 28x_{21}+26x_{22}+30x_{23}+39x_{24} \\
        &+ 24x_{31}+25x_{32}+34x_{33}+27x_{34} \\
        &+ 28x_{41}+26x_{42}+28x_{43}+25x_{44}
\end{align*}]{.light-blue}

:::

## Örnek 3: İş - Tezgah Eşleştirme (3)

::: {.callout-tip icon=false title="Kısıtlar" style="font-size: 120%;"}

::: columns

::: {.column width="45%"}

[İş Kısıtları]{.red}
[$$
\begin{alignedat}{7}
x_{11} &+& x_{12}  &+& x_{13} &+& x_{14}  &\;= & 1\\
x_{21} &+& x_{22}  &+& x_{23} &+& x_{24}  &\;= & 1\\
x_{31} &+& x_{32}  &+& x_{33} &+& x_{34}  &\;= & 1\\
x_{41} &+& x_{42}  &+& x_{43} &+& x_{44}  &\;= & 1
\end{alignedat}
$$]{.light-blue}
:::

::: {.column width="10%"}
:::

::: {.column width="45%"}
[Tezgah Kısıtları]{.red}
[$$
\begin{alignedat}{7}
x_{11} &+& x_{21}  &+& x_{31} &+& x_{41} &\;= & 1\\
x_{12} &+& x_{22}  &+& x_{32} &+& x_{42} &\;= & 1\\
x_{13} &+& x_{23}  &+& x_{33} &+& x_{43} &\;= & 1\\
x_{14} &+& x_{24}  &+& x_{34} &+& x_{44} &\;= & 1
\end{alignedat}
$$]{.light-blue}
:::
[İşaret kısıtlaması:]{.red}
Son olarak negatif atama olmayacağına göre 
[$$x_{ij} \geq 0; \quad{} i = 1,2 \dots, 4; \quad{} j = 1,2 \dots, 4;$$]{.light-blue}
:::
:::


## Örnek 3: İş - Tezgah Eşleştirme (4)


::: {.callout-tip icon=false title="Başlangıç Tablosu" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 0: Başlangıç Tablosu]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_00_initial.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}

:::
:::

:::

## Örnek 3: İş - Tezgah Eşleştirme (5)


::: {.callout-tip icon=false title="Satır İndirgeme" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 1: Satır İndirgenmiş Matris]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_02_.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}


:::
:::

:::

## Örnek 3: İş - Tezgah Eşleştirme (6)


::: {.callout-tip icon=false title="Sütun İndirgeme" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 2: Sütun İndirgenmiş Matris]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_03_.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}


:::
:::

:::

## Örnek 3: İş - Tezgah Eşleştirme (7)


::: {.callout-tip icon=false title="Kapsama Kontrolü" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 3: Kapsama Kontrolü]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_05_.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}





:::
:::

:::


## Örnek 3: İş - Tezgah Eşleştirme (8)


::: {.callout-tip icon=false title="Çizgi Değiştirme" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 4: Çizgi Değiştirme]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_07_.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}



:::
:::

:::

## Örnek 3: İş - Tezgah Eşleştirme (9)


::: {.callout-tip icon=false title="Değer Güncelleme ve Kapsam Kontrolü" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 4: Değer Güncelleme]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_08_.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}

:::
:::

:::



## Örnek 3: İş - Tezgah Eşleştirme (10)


::: {.callout-tip icon=false title="Tekrar Kapsam Kontrolü" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Adım 3: Tekrar Kapsam Kontrolü]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_15_.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}


:::
:::

:::



## Örnek 3: İş - Tezgah Eşleştirme (11)


::: {.callout-tip icon=false title="Optimum hücrelerin belirlenmesi" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Çözüm: Optimum hücrelerin belirlenmesi]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_15_final_zero_matrix.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}
:::{.fragment fragment-index=1}

[İş 1 $\rightarrow$ Tezgah 4]{.light-blue} e, <br>
[İş 2 $\rightarrow$ Tezgah 2]{.light-blue} e, <br>
[İş 3 $\rightarrow$ Tezgah 1]{.light-blue} e ve <br>
[İş 4 $\rightarrow$ Tezgah 3]{.light-blue} e atanır.


:::

:::
:::

:::

## Örnek 3: İş - Tezgah Eşleştirme (12)


::: {.callout-tip icon=false title="Optimum değerin belirlenmesi" style="font-size: 110%;"}

::: columns

::: {.column width="66%"}
[Çözüm: Optimum değerin belirlenmesi]{.red}

:::{.tblbox .tbl-fs-xl .w-100 .scale-150  .pad-cozy .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\examples\example1_assignment\EX1_16_final_assignment_01.html >}}
```
:::

:::
::: {.column width="3%"}
:::

::: {.column width="30%"}
:::{.fragment fragment-index=1 style="font-size: 90%;"}

[Başlangıç tablosunda atama yapılan hücrelerin değerleri toplanarak]{.light-red} [optimum değer]{.light-blue} bulunur.

[$$24+26+28+22=100$$]{.light-blue}

[Dört]{.light-blue} iş için harcanabilecek [en düşük süre]{.light-blue} [100 dk]{.orange} dır.

:::

:::
:::

:::
