---
title: Hafta 06
subtitle: "Simpleks Yöntem: Büyük M yöntemi - Minimizasyon"
date: 10/23/2025
date-format: DD/MM/YYYY
author: "Doç. Dr. Erhan Çene"
format: 
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: true
    preview-links: auto
    logo: images/iticulogo.png
    css: styles.css
    footer: "IST115 - Doğrusal Programlama 1 - Hafta 06 - 23 Ekim 2025 - Doç. Dr. Erhan Çene"
    # width: 2000
    # height: 1500
filters:
  - parse-latex
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
---


## Büyük M Yöntemi (1)

::: {.callout-important icon=false title="Simpleks Çözüm Yöntemi (1)" style="font-size: 120%;"}


* Simpleks yöntemin en basit versiyonunu tüm kısıtların [$\leq$]{.light-red} biçiminde verildiği durum için geçtiğimiz hafta uyguladık.
* Kısıtların [$=$]{.light-red} ya da [$\geq$]{.light-red} olarak verildiği durumlarda ise [Yapay başlangıç yöntemleri]{.light-red} kullanılır.
* Bu yöntemler arasında [$M$ Yöntemi]{.light-red} ve [İki Aşamalı Yöntem]{.light-red} sayılabilir.
* Bu hafta bu yöntemler arasından [$M$ Yöntemi]{.light-red} ni [minimzasyon soruları için]{.light-red} göreceğiz.
:::



## Büyük M Yöntemi (2)

::: {.callout-important icon=false title="Büyük M Yöntemi (2)" style="font-size: 120%;"}


* [$M$]{.light-red} yönteminde çözüme [standart halle]{.light-red} başlanır.
* Denklemler standart hale getirilirken, geçtiğimiz haftalarda öğrenilen yöntemler ile [dolgu değişken $s_i$ ler]{.light-red} eklenir. 
* Kısıtlar standart hale getirildikten sonra, başlangıçta [$=$]{.light-red} ya da [$\geq$]{.light-red} biçiminde kısıta sahip olan denklemlere [$A_i$]{.light-red} yapay değişkenleri eklenir.
* Yapay değişkenler aslında modele sonradan giren yabancı değişkenler olduklarından, simpleks algoritmanın sonraki yinelemelerinde [sıfır]{.light-red} değerini alarak temel dışına çıkmalarını sağlamak için, bu değişkenlere amaç fonksiyonunda bir [ceza katsayısı]{.light-red} verilir.
:::


## Büyük M Yöntemi (3)

::: {.callout-important icon=false title="Büyük M Yöntemi (3)" style="font-size: 120%;"}

* Verilen bu [$M$]{.light-red} ceza katsayısı yeterince büyük, pozitif bir sayıdır.
* Amaç fonksiyonu [maksimum]{.light-red} ise, [$A_i$]{.light-red} yapay değişkeninin katsayısı [$-M$]{.light-red}; [minimum]{.light-red} ise, [$A_i$]{.light-red} yapay değişkeninin katsayısı [$+M$]{.light-red} olacaktır.
* Optimizasyon işlemlerinin doğası gereği, temel değişkenleri ilk terk edecek değişkenler [$A_i$ yapay değişkenleri]{.light-red} olacaktır.
:::

## Örnek 1: Büyük M Minimizasyon Problemi (1)

::: {.callout-tip icon=false title="Örnek 1: Büyük M Minimizasyon Problemi (1)" style="font-size: 120%;"}

::: columns
::: {.column width="40%"}
Aşağıdaki doğrusal programlama problemini simpleks yöntemle çözünüz.

[$Z_{min}=3x_1+2x_2+x_3$]{.light-blue}

[$2x_1 + 3x_2 + x_3  \geq 21$]{.light-blue}

[$x_1 + x_2 + x_3 \geq 12$]{.light-blue}


[$x_1$, $x_2$, and $x_3 \geq 0$]{.light-blue}


:::


::: {.column width="1%"}

:::

::: {.column width="59%"}

:::{.fragment fragment-index=5}
[Standart Form:]{.red}
:::

:::{.fragment fragment-index=6 style="font-size: 100%;"}
\begin{multline}
Z_{min}=2x_1+3x_2 \\ 
 \color{orange}{+0s_1+0s_2}
 \color{green}{+MA_1+MA_2}
\end{multline}
:::


:::{.fragment fragment-index=7 style="font-size: 85%;"}

$$
\begin{alignedat}{7}
2x_1 &+& 3x_2 &+& 1x_3 &\color{orange}-& {\color{orange} {1s_1 + 0s_2}}{\color{green} {+1A_1 + 0A_2}} &\;\color{orange}= & 21,\\
1x_1 &+& 1x_2 &+& 1x_3 &\color{orange}+& {\color{orange} {0s_1 - 1s_2}}{\color{green} {+0A_1 + 1A_2}} &\;\color{orange}= & 12
\end{alignedat}
$$

:::

:::{.fragment fragment-index=8 style="font-size: 95%;"}
$x_1$, $x_2$, $x_3 \geq 0$, [$s_1$, $s_2 \geq 0$]{.orange} ve [$A_1$ , $A_2 \geq 0$]{.green} 

:::

:::

:::

:::


## Örnek 1: Büyük M Minimizasyon Problemi (2)

::: {.callout-tip icon=false title="Örnek 1: Başlangıç Tablosu" style="font-size: 100%;"}

::: columns

::: {.column width="73%"}
:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_01_before.html >}}
```
:::


:::




::: {.column width="1%"}

:::

::: {.column width="20%"}
:::

:::
:::

## Örnek 1: Büyük M Minimizasyon Problemi (3)

::: {.callout-tip icon=false title="Örnek 1: $Z_j$ ve $Z_j-C_j$ (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="80%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_02_write.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::


## Örnek 1: Büyük M Minimizasyon Problemi (4)

::: {.callout-tip icon=false title="Örnek 1: Anahtar Sütun (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_03_enter_col.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::

## Örnek 1: Büyük M Minimizasyon Problemi (5)

::: {.callout-tip icon=false title="Örnek 1: Anahtar Satır (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_04_select.html >}}
```
:::

:::{style="font-size: 90%;"}
* [$4M-2$]{.green} en büyük değer olduğundan [$x_2$]{.red} [anahtar sütun]{.light-blue} dur.

:::
:::

::: {.column width="1%"}

:::

::: {.column width="25%"}

:::{style="font-size: 90%;"}
* En düşük oran [$7$]{.red} olduğundan [$a_1$]{.red} [anahtar satırdır]{.light-blue}.
* Anahtar sayı [$3$]{.red} olduğundan [$a_1$]{.light-blue} satırı [$\frac{1}{3}$]{.light-blue} ile çarpılır.
* Temel değişkenlerden [$a_1$]{.red} çözümden çıkarken, [$x_2$]{.red} çözüme girer.
* Anahtar satır, [$-1$]{.light-blue} ile çarpılarak [$a_1$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 1: Büyük M Minimizasyon Problemi (6)

::: {.callout-tip icon=false title="Örnek 1: Anahtar Satır İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_05_update_base_row.html >}}
```
:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 93%;"}
[Anahtar satır için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 2 \\ 3 \\ 1 \\ -1 \\ 0 \\ 1 \\ 0 \\ 21 \end{pmatrix} \times \frac{1}{3} = \begin{pmatrix} 0.67 \\ 1 \\ 0.33 \\ -0.33 \\ 0 \\ 0.33 \\0 \\ 7 \end{pmatrix}$$
:::

:::

:::

:::




## Örnek 1: Büyük M Minimizasyon Problemi (7)

::: {.callout-tip icon=false title="Örnek 1: Diğer Satırlar İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_06_update_other_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="35%"}

:::{style="font-size: 75%;"}
[Diğer satırlar için değerlerin hesaplanması $a_2$]{.red}

$$\begin{pmatrix} 1 \\ 1 \\ 1 \\ 0 \\ -1 \\ 0 \\ 1 \\ 12 \end{pmatrix} - 1 \times \begin{pmatrix} 0.67 \\ 1 \\ 0.33 \\ -0.33 \\ 0 \\ 0.33 \\0 \\ 7 \end{pmatrix}= \begin{pmatrix} 0.33 \\ 0 \\ 0.67 \\ 0.33 \\ -1 \\ -0.33 \\ 1 \\ 5 \end{pmatrix} $$

:::
:::

:::

:::


## Örnek 1: Büyük M Minimizasyon Problemi (8)

::: {.callout-tip icon=false title="Örnek 1: Simpleks Adım Sonu (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="84%"}

:::{.tblbox .tbl-fs-lg .w-100 .scale-100 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter01_07_after_objective.html >}}
```
:::
* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.
:::


::: {.column width="1%"}

:::

::: {.column width="15%"}

:::{style="font-size: 90%;"}
* [$5M+14$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}
:::
:::

:::

:::


## Örnek 1: Büyük M Minimizasyon Problemi (9)

::: {.callout-tip icon=false title="Örnek 1: Anahtar Satır, Sütun ve Anahtar Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="75%"}

:::{.tblbox .tbl-fs-lg .w-100 .scale-100 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter02_04_select.html >}}
```
:::

* [$0.67M+0.67$]{.green} en büyük değer olduğundan [$x_3$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$7.5$]{.red} olduğundan [$a_2$]{.red} [anahtar satırdır]{.light-blue}.
:::


::: {.column width="1%"}

:::

::: {.column width="23%"}

* Anahtar sayı [$0.67$]{.red} olduğundan [$a_2$]{.light-blue} satırı [$\frac{3}{2}$]{.light-blue} ile çarpılmalıdır.
* Temel değişkenlerden [$a_2$]{.red} çözümden çıkarken, [$x_3$]{.red} çözüme girer.
* Anahtar satır, [$-0.33$]{.light-blue} ile çarpılarak [$x_2$]{.light-blue} ile toplanır.

:::

:::

:::


## Örnek 1: Büyük M Minimizasyon Problemi (10)

::: {.callout-tip icon=false title="Örnek 1: Anahtar Satır İçin Yeni Değerler (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-lg .w-100 .scale-150 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter02_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


[Anahtar satır için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 0.33 \\ 0 \\ 0.67 \\ 0.33 \\ -1 \\ -0.33 \\ 1 \\ 5  \end{pmatrix} \times \frac{3}{2} = \begin{pmatrix} 0.50 \\ 0 \\ 1 \\ 0.50 \\ -1.50 \\ -0.50 \\ 1.50 \\ 7.50 \end{pmatrix}$$
:::

:::

:::

:::



## Örnek 1: Büyük M Minimizasyon Problemi (11)

::: {.callout-tip icon=false title="Örnek 1: Diğer Satırlar İçin Yeni Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-lg .w-100 .scale-150 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter02_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 65%;"}

[Diğer satırlar için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 0.67 \\ 1 \\ 0.33  \\ -0.33 \\0\\ 0.33 \\ 0 \\ 7 \end{pmatrix} - 0.33 \times \begin{pmatrix} 0.50 \\ 0 \\ 1 \\ 0.50 \\ -1.50 \\ -0.50 \\ 1.50 \\ 7.50 \end{pmatrix}= \begin{pmatrix} 0.50 \\ 1 \\ 0 \\ -0.50 \\ 0.50 \\ 0.50 \\ -0.50 \\ 4.50 \end{pmatrix} $$
:::
:::

:::

:::


## Örnek 1: Büyük M Minimizasyon Problemi (12)

::: {.callout-tip icon=false title="Örnek 1: Simpleks Adım Sonu (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-lg .w-100 .scale-150 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex1\ex1_iter02_07_after_objective.html >}}
```

:::

* [$Z_j - C_j$]{.light-blue} değerlerinin tamamı [$\leq 0$]{.light-blue} olduğundan çözüm optimuma ulaşmıştır.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

* Son durumda [$Z = 16.50$]{.light-blue} amaç fonksiyonu için bulunabilecek en küçük değerdir.
* Bu çözümde [$x_1 = 0$]{.light-blue}, [$x_2 =4.5$]{.light-blue}, [$x_3 =7.5$]{.light-blue}, [$s_1 =0$]{.light-blue}, [$s_2 = 0$]{.light-blue}, [$a_1=0$]{.light-blue}  ve [$a_2 = 0$]{.light-blue}’dır.
:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (1)

::: {.callout-tip icon=false title="Örnek 2: Büyük M Minimizasyon Problemi (1)" style="font-size: 120%;"}

::: columns
::: {.column width="40%"}
Aşağıdaki doğrusal programlama problemini simpleks yöntemle çözünüz.

[$Z_{min}=10x_1+6x_2+8x_3$]{.light-blue}

[$x_1 + x_2 + 2x_3 \geq 2$]{.light-blue}

[$5x_1 + 3x_2 + 2x_3 \geq 1$]{.light-blue}

[$x_1$, $x_2$, ve $x_3 \geq 0$]{.light-blue}


:::


::: {.column width="1%"}

:::

::: {.column width="59%"}

:::{.fragment fragment-index=5}
[Standart Form:]{.red}
:::

:::{.fragment fragment-index=6 style="font-size: 100%;"}
\begin{multline}
Z_{min}=10x_1+6x_2+8x_3 \\ 
\color{orange}{+0s_1+0s_2} \color{green}{+MA_1+MA_2}
\end{multline}
:::


:::{.fragment fragment-index=7 style="font-size: 90%;"}

$$
\begin{alignedat}{7}
1x_1 &+& 1x_2 &+& 2x_3 &\color{orange}-& {\color{orange} {1s_1 + 0s_2}}{\color{green} {+1A_1 + 0A_2}} &\;\color{orange}= & 2,\\
5x_1 &+& 3x_2 &+& 2x_3 &\color{orange}+& {\color{orange} {0s_1 -1s_2}}{\color{green} {+0A_1 + 1A_2}} &\;\color{orange}= & 1
\end{alignedat}
$$
:::

:::{.fragment fragment-index=8 style="font-size: 90%;"}
$x_1$, $x_2$, ve $x_3 \geq 0$, [$s_1$ , $s_2 \geq 0$]{.orange} ve [$A_1$ , $A_2 \geq 0$]{.green} 

:::

:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (2)

::: {.callout-tip icon=false title="Örnek 2: Başlangıç Tablosu" style="font-size: 100%;"}

::: columns

::: {.column width="80%"}
:::{.tblbox .tbl-fs-xl .w-100 .scale-150 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_01_before.html >}}
```
:::


:::




::: {.column width="1%"}

:::

::: {.column width="20%"}
:::

:::
:::

## Örnek 2: Büyük M Minimizasyon Problemi (3)

::: {.callout-tip icon=false title="Örnek 2: $Z_j$ ve $Z_j-C_j$ (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="80%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_02_write.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::


## Örnek 2: Büyük M Minimizasyon Problemi (4)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Sütun (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_03_enter_col.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::

## Örnek 2: Büyük M Minimizasyon Problemi (5)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Satır (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_04_select.html >}}
```
:::
* [$6M-10$]{.green} en büyük değer olduğundan [$x_1$]{.red} [anahtar sütun]{.light-blue} dur.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}
* En düşük oran [$0.20$]{.red} olduğundan [$a_2$]{.red} [anahtar satırdır]{.light-blue}.
* Anahtar sayı [$5$]{.red} olduğundan [$a_2$]{.light-blue} satırı [$\frac{1}{5}$]{.light-blue} ile çarpılır.
* Temel değişkenlerden [$a_2$]{.red} çözümden çıkarken, [$x_1$]{.red} çözüme girer.
* Anahtar satır, [$-1$]{.light-blue} ile çarpılarak [$a_1$]{.light-blue} ile toplanır.

:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (6)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Satır İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_05_update_base_row.html >}}
```
:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 93%;"}
[Anahtar satır için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 5 \\ 3 \\ 2 \\ 0 \\ -1 \\ 0 \\ 1 \\ 1 \\ 1 \end{pmatrix} \times \frac{1}{5} = \begin{pmatrix} 1 \\ 0.60 \\ 0.40 \\ 0 \\ -0.20 \\ 0 \\ 0.20 \\ 0.20  \end{pmatrix}$$
:::

:::

:::

:::




## Örnek 2: Büyük M Minimizasyon Problemi (7)

::: {.callout-tip icon=false title="Örnek 2: Diğer Satırlar İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_06_update_other_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="35%"}

:::{style="font-size: 75%;"}
[Diğer satırlar için değerlerin hesaplanması $a_1$]{.red}

$$\begin{pmatrix} 1 \\ 1 \\ 2\\ -1 \\ 0 \\ 1 \\ 0 \\ 2 \end{pmatrix} - 1 \times \begin{pmatrix} 1 \\ 0.60 \\ 0.40 \\ 0 \\ -0.20 \\ 0 \\ 0.20 \\ 0.20  \end{pmatrix} = \begin{pmatrix} 0 \\ 0.40 \\ 1.60 \\ -1 \\ 0.20 \\ 1 \\ -0.20 \\ 1.80 \end{pmatrix}$$
:::
:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (8)

::: {.callout-tip icon=false title="Örnek 2: Simpleks Adım Sonu (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="84%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter01_07_after_objective.html >}}
```
:::
* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.
:::


::: {.column width="1%"}

:::

::: {.column width="15%"}


* [$1.8M+2$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}

:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (9)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Satır, Sütun ve Anahtar Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}

:::{.tblbox .tbl-fs-md .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter02_04_select.html >}}
```
:::

* [$1.6M+4$]{.green} en büyük değer olduğundan [$x_3$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$0.50$]{.red} olduğundan [$x_1$]{.red} [anahtar satırdır]{.light-blue}.
:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::{style="font-size: 100%;"}
* Anahtar sayı [$0.40$]{.red} olduğundan [$x_1$]{.light-blue} satırı [$0.40$]{.light-blue} ile bölünmelidir.
* Temel değişkenlerden [$x_1$]{.red} çözümden çıkarken, [$x_3$]{.red} çözüme girer.
* Anahtar satır [$-1.60$]{.light-blue} ile çarpılarak [$a_1$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (10)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Satır İçin Yeni Değerler (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter02_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


[Anahtar satır için değerlerin hesaplanması $x_3$]{.red}

$$\begin{pmatrix} 1 \\ 0.60 \\ 0.40 \\ 0 \\ -0.20 \\ 0 \\ 0.20 \\ 0.20 \end{pmatrix} \div 0.40 = \begin{pmatrix} 2.50 \\ 1.50 \\ 1 \\ 0 \\ -0.50 \\ 0 \\ 0.50 \\ 0.50 \end{pmatrix}$$
:::

:::

:::

:::



## Örnek 2: Büyük M Minimizasyon Problemi (11)

::: {.callout-tip icon=false title="Örnek 2: Diğer Satırlar İçin Yeni Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter02_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="39%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $a_1$]{.red}

$$\begin{pmatrix} 0 \\ 0.40 \\ 1.60 \\ -1 \\ 0.20 \\ 1 \\ -0.20 \\ 1.80 \end{pmatrix} - 1.60 \times \begin{pmatrix} 2.50 \\ 1.50 \\ 1 \\ 0 \\ -0.50 \\ 0 \\ 0.50 \\ 0.50  \end{pmatrix} = \begin{pmatrix} -4 \\ -2 \\ 0 \\ -1 \\ 1 \\ 1 \\ -1 \\ 1 \end{pmatrix} $$


:::
:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (12)

::: {.callout-tip icon=false title="Örnek 2: Simpleks Adım Sonu (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter02_07_after_objective.html >}}
```

:::

* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

* [$M+4$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}
:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (13)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Satır, Sütun ve Anahtar Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter03_04_select.html >}}
```
:::

* [$M-4$]{.green} en büyük değer olduğundan [$s_2$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$1$]{.red} olduğundan [$a_1$]{.red} [anahtar satırdır]{.light-blue}. 
:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::{style="font-size: 85%;"}

* Anahtar sayı [$1$]{.red} olduğundan [$a_1$]{.light-blue} satırı aynı kalabilir.
* Temel değişkenlerden [$a_1$]{.red} çözümden çıkarken, [$s_2$]{.red} çözüme girer.
* Anahtar satır [$\frac{1}{2}$]{.light-blue} ile çarpılarak [$x_3$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (14)

::: {.callout-tip icon=false title="Örnek 2: Anahtar Satır İçin Yeni Değerler (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter03_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


:::

:::

:::

:::

## Örnek 2: Büyük M Minimizasyon Problemi (15)

::: {.callout-tip icon=false title="Örnek 2: Diğer Satırlar İçin Yeni Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter03_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="39%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $x_3$]{.red}

$$\begin{pmatrix} 2.50 \\ 1.50 \\ 1 \\ 0 \\ -0.50 \\ 0 \\ 0.50 \\ 0.50 \end{pmatrix} + 0.50 \times \begin{pmatrix} -4 \\ -2 \\ 0 \\ -1 \\ 1 \\ 1 \\ -1 \\ 1  \end{pmatrix} = \begin{pmatrix} 0.50 \\ 0.50 \\ 1 \\ -0.50 \\ 0\\ 0.50 \\ 0 \\ 1 \end{pmatrix} $$


:::
:::

:::

:::

## Örnek 2: Büyük M Minimizasyon Problemi (16)

::: {.callout-tip icon=false title="Örnek 2: Diğer Satırlar İçin Yeni Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="70%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter03_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="29%"}

:::

:::

:::


## Örnek 2: Büyük M Minimizasyon Problemi (17)

::: {.callout-tip icon=false title="Örnek 2: Simpleks Adım Sonu (İter 3)" style="font-size: 80%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex2\ex2_iter03_07_after_objective.html >}}
```

:::



:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

:::{style="font-size: 120%;"}
* Son durumda [$Z=8$]{.light-blue} amaç fonksiyonu için bulunabilecek en küçük değerdir.
* Bu çözümde [$x_1 = 0$]{.light-blue}, [$x_2 =0$]{.light-blue}, [$x_3 =1$]{.light-blue} [$s_1 = 0$]{.light-blue}, [$s_2=1$]{.light-blue}, [$a_1=0$]{.light-blue}  ve [$a_2 = 0$]{.light-blue}’dır.
:::

:::

:::

:::{style="font-size: 120%;"}

* [$z_j-c_j$]{.light-blue} değerlerinin tamamı [$\leq 0$]{.light-blue} olduğundan çözüm optimuma ulaşmıştır.
:::
:::


## Örnek 3: Büyük M Minimizasyon Problemi (1)

::: {.callout-tip icon=false title="Örnek 3: Büyük M Minimizasyon Problemi (1)" style="font-size: 120%;"}

::: columns
::: {.column width="40%"}
Aşağıdaki doğrusal programlama problemini simpleks yöntemle çözünüz.

[$Z_{min}=2x_1+3x_2-5x_3$]{.light-blue}

[$x_1 + x_2 + x_3 = 7$]{.light-blue}

[$2x_1 - 5x_2 + x_3 \geq 10$]{.light-blue}

[$x_1$, $x_2$, ve $x_3 \geq 0$]{.light-blue}


:::


::: {.column width="1%"}

:::

::: {.column width="59%"}

:::{.fragment fragment-index=5}
[Standart Form:]{.red}
:::

:::{.fragment fragment-index=6 style="font-size: 100%;"}
\begin{multline}
Z_{min}=2x_1+3x_2-5x_3\\ 
\color{orange}{+0s_1} \color{green}{+MA_1+MA_2}
\end{multline}
:::


:::{.fragment fragment-index=7 style="font-size: 90%;"}

$$
\begin{alignedat}{7}
1x_1 &+& 1x_2 &+& 1x_3 &\color{orange}+& {\color{orange} {0s_1}}{\color{green} {+1A_1 + 0A_2}} &\;\color{orange}= & 7,\\
2x_1 &-& 5x_2 &+& 1x_3 &\color{orange}-& {\color{orange} {1s_1}}{\color{green} {+0A_1 + 1A_2}} &\;\color{orange}= & 10
\end{alignedat}
$$
:::

:::{.fragment fragment-index=8 style="font-size: 90%;"}
$x_1$, $x_2$, ve $x_3 \geq 0$, [$s_1 \geq 0$]{.orange} ve [$A_1$ , $A_2 \geq 0$]{.green} 

:::

:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (2)

::: {.callout-tip icon=false title="Örnek 3: Başlangıç Tablosu" style="font-size: 100%;"}

::: columns

::: {.column width="80%"}
:::{.tblbox .tbl-fs-xl .w-100 .scale-150 .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_01_before.html >}}
```
:::


:::




::: {.column width="1%"}

:::

::: {.column width="20%"}
:::

:::
:::

## Örnek 3: Büyük M Minimizasyon Problemi (3)

::: {.callout-tip icon=false title="Örnek 3: $Z_j$ ve $Z_j-C_j$ (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="80%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_02_write.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::


## Örnek 3: Büyük M Minimizasyon Problemi (4)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Sütun (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_03_enter_col.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::

## Örnek 3: Büyük M Minimizasyon Problemi (5)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Satır (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_04_select.html >}}
```
:::
* [$3M-2$]{.green} en büyük değer olduğundan [$x_1$]{.red} [anahtar sütun]{.light-blue} dur.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}
* En düşük oran [$5$]{.red} olduğundan [$a_2$]{.red} [anahtar satırdır]{.light-blue}.
* Anahtar sayı [$2$]{.red} olduğundan [$a_2$]{.light-blue} satırı [$\frac{1}{2}$]{.light-blue} ile çarpılır.
* Temel değişkenlerden [$a_2$]{.red} çözümden çıkarken, [$x_1$]{.red} çözüme girer.
* Anahtar satır, [$-1$]{.light-blue} ile çarpılarak [$a_1$]{.light-blue} ile toplanır.

:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (6)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Satır İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_05_update_base_row.html >}}
```
:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 93%;"}
[Anahtar satır için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 2 \\ -5 \\ 1 \\ -1 \\ 0 \\ 1 \\ 10 \end{pmatrix} \times \frac{1}{2} = \begin{pmatrix} 1 \\ -2.5 \\ 0.50 \\ -0.50 \\ 0 \\ 0.50 \\ 5  \end{pmatrix}$$
:::

:::

:::

:::




## Örnek 3: Büyük M Minimizasyon Problemi (7)

::: {.callout-tip icon=false title="Örnek 3: Diğer Satırlar İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_06_update_other_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="35%"}

:::{style="font-size: 75%;"}
[Diğer satırlar için değerlerin hesaplanması $a_1$]{.red}

$$\begin{pmatrix} 1 \\ 1 \\ 1\\ 0 \\ 1 \\ 0 \\ 7 \end{pmatrix} - 1 \times \begin{pmatrix} 1 \\ -2.5 \\ 0.50 \\ -0.50 \\ 0 \\ 0.50 \\ 5  \end{pmatrix} = \begin{pmatrix} 0 \\ 3.50 \\ 0.50 \\ 0.50 \\ 1 \\ -0.50 \\ 2 \end{pmatrix}$$
:::
:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (8)

::: {.callout-tip icon=false title="Örnek 3: Simpleks Adım Sonu (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="84%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter01_07_after_objective.html >}}
```
:::
* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.
:::


::: {.column width="1%"}

:::

::: {.column width="15%"}


* [$1.8M+2$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}

:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (9)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Satır, Sütun ve Anahtar Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}

:::{.tblbox .tbl-fs-md .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter02_04_select.html >}}
```
:::

* [$3.5M-8$]{.green} en büyük değer olduğundan [$x_2$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$0.57$]{.red} olduğundan [$x_2$]{.red} [anahtar satırdır]{.light-blue}.
:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::{style="font-size: 100%;"}
* Anahtar sayı [$3.50$]{.red} olduğundan [$a_1$]{.light-blue} satırı [$3.50$]{.light-blue} ile bölünmelidir.
* Temel değişkenlerden [$a_1$]{.red} çözümden çıkarken, [$x_2$]{.red} çözüme girer.
* Anahtar satır [$2.50$]{.light-blue} ile çarpılarak [$x_1$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (10)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Satır İçin Yeni Değerler (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter02_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


[Anahtar satır için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 0 \\ 3.50 \\ 0.50 \\ 0.50 \\ 1 \\ -0.50 \\ 2 \end{pmatrix} \div 3.50 = \begin{pmatrix} 0 \\ 1 \\ 0.14 \\ 0.14 \\ 0.29 \\ -0.14 \\ 0.57 \end{pmatrix}$$
:::

:::

:::

:::



## Örnek 3: Büyük M Minimizasyon Problemi (11)

::: {.callout-tip icon=false title="Örnek 3: Diğer Satırlar İçin Yeni Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter02_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="39%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 1 \\ -2.50 \\ 0.50 \\ -0.50 \\ 0 \\ 0.50 \\ 5 \end{pmatrix} + 2.50 \times \begin{pmatrix} 0 \\ 1 \\ 0.14 \\ 0.14 \\ 0.29 \\ -0.14 \\ 0.57 \end{pmatrix} = \begin{pmatrix} 1 \\ 0 \\ 0.86 \\ -0.14 \\ 0.71 \\ 0.14\\ 6.43 \end{pmatrix}$$


:::
:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (12)

::: {.callout-tip icon=false title="Örnek 3: Simpleks Adım Sonu (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter02_07_after_objective.html >}}
```

:::

* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

* [$14.57$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}
:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (13)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Satır, Sütun ve Anahtar Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter03_04_select.html >}}
```
:::

* [$7.14$]{.green} en büyük değer olduğundan [$x_3$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$4$]{.red} olduğundan [$x_2$]{.red} [anahtar satırdır]{.light-blue}. 
:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::{style="font-size: 85%;"}

* Anahtar sayı [$0.14$]{.red} olduğundan [$x_2$]{.light-blue} satırı  [$0.14$]{.light-blue} ile bölünmelidir.
* Temel değişkenlerden [$x_2$]{.red} çözümden çıkarken, [$x_3$]{.red} çözüme girer.
* Anahtar satır [$-0.86$]{.light-blue} ile çarpılarak [$x_1$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 3: Büyük M Minimizasyon Problemi (14)

::: {.callout-tip icon=false title="Örnek 3: Anahtar Satır İçin Yeni Değerler (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter03_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}
[Anahtar satır için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 0 \\ 1 \\ 0.14 \\ 0.14 \\ 0.29 \\ -0.14 \\ 0.57 \end{pmatrix} \div 0.14 = \begin{pmatrix} 0 \\ 7 \\ 1 \\ 1 \\ 2 \\ -1 \\ 4 \end{pmatrix}$$

:::

:::

:::

:::

## Örnek 3: Büyük M Minimizasyon Problemi (15)

::: {.callout-tip icon=false title="Örnek 3: Diğer Satırlar İçin Yeni Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter03_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="39%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 1 \\ 0 \\ 0.86 \\ -0.14 \\ 0.71 \\ 0.14 \\ 6.43 \end{pmatrix} -0.86 \times  \begin{pmatrix} 0 \\ 7 \\ 1 \\ 1 \\ 2 \\ -1 \\ 4 \end{pmatrix} = \begin{pmatrix} 1 \\ -6 \\ 0 \\ -1 \\ -1\\ 1 \\ 3 \end{pmatrix} $$


:::
:::

:::

:::

## Örnek 3: Büyük M Minimizasyon Problemi (16)

::: {.callout-tip icon=false title="Örnek 3: Simpleks Adım Sonu (İter 3)" style="font-size: 80%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex3\ex3_iter03_07_after_objective.html >}}
```

:::



:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

:::{style="font-size: 120%;"}
* Son durumda [$Z=-14$]{.light-blue} amaç fonksiyonu için bulunabilecek en küçük değerdir.
* Bu çözümde [$x_1 = 3$]{.light-blue}, [$x_2 =0$]{.light-blue}, [$x_3 =4$]{.light-blue} [$s_1 = 0$]{.light-blue}, [$a_1=0$]{.light-blue}  ve [$a_2 = 0$]{.light-blue}’dır.
:::

:::

:::

:::{style="font-size: 120%;"}

* [$z_j-c_j$]{.light-blue} değerlerinin tamamı [$\leq 0$]{.light-blue} olduğundan çözüm optimuma ulaşmıştır.
:::
:::

## Örnek 4: Büyük M Minimizasyon Problemi (1)

::: {.callout-tip icon=false title="Örnek 4: Büyük M Minimizasyon Problemi (1)" style="font-size: 120%;"}

::: columns
::: {.column width="40%"}
Aşağıdaki doğrusal programlama problemini simpleks yöntemle çözünüz.

[$Z_{min}=4x_1+x_2$]{.light-blue}

[$3x_1 + x_2 = 3$]{.light-blue}

[$4x_1 + 3x_2 \geq 6$]{.light-blue}

[$x_1 + 2x_2 \leq 4$]{.light-blue}

[$x_1$ ,$x_2 \geq 0$]{.light-blue}


:::


::: {.column width="1%"}

:::

::: {.column width="59%"}

:::{.fragment fragment-index=5}
[Standart Form:]{.red}
:::

:::{.fragment fragment-index=6 style="font-size: 100%;"}
\begin{multline}
Z_{min}=4x_1+x_2 \\ 
\color{orange}{+0s_1+0s_2} \color{green}{+MA_1+MA_2}
\end{multline}
:::


:::{.fragment fragment-index=7 style="font-size: 90%;"}

$$
\begin{alignedat}{7}
3x_1 &+& x_2 &\color{orange}+& {\color{orange} {0s_1 + 0s_2}}{\color{green} {+1A_1 + 0A_2}} &\;\color{orange}= & 3,\\
4x_1 &+& 3x_2 &\color{orange}-& {\color{orange} {1s_1 +0s_2}}{\color{green} {+0A_1 + 1A_2}} &\;\color{orange}= & 6,\\
x_1 &+& 2x_2 &\color{orange}+& {\color{orange} {0s_1 +1s_2}}{\color{green} {+0A_1 + 0A_2}} &\;\color{orange}= & 4
\end{alignedat}
$$
:::

:::{.fragment fragment-index=8 style="font-size: 95%;"}
$x_1$, $x_2 \geq 0$, [$s_1$ , $s_2 \geq 0$]{.orange} ve [$A_1$ , $A_2 \geq 0$]{.green} 

:::

:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (2)

::: {.callout-tip icon=false title="Örnek 4: Başlangıç Tablosu" style="font-size: 100%;"}

::: columns

::: {.column width="80%"}
:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_01_before.html >}}
```
:::


:::




::: {.column width="1%"}

:::

::: {.column width="20%"}
:::

:::
:::

## Örnek 4: Büyük M Minimizasyon Problemi (3)

::: {.callout-tip icon=false title="Örnek 4: $Z_j$ ve $Z_j-C_j$ (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="80%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_02_write.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::


## Örnek 4: Büyük M Minimizasyon Problemi (4)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Sütun (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_03_enter_col.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::

## Örnek 4: Büyük M Minimizasyon Problemi (5)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Satır (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_04_select.html >}}
```
:::

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

:::{style="font-size: 80%;"}
* En düşük oran [$1$]{.red} olduğundan [$a_1$]{.red} [anahtar satırdır]{.light-blue}.
* Anahtar sayı [$3$]{.red} olduğundan [$a_1$]{.light-blue} satırı [$\frac{1}{3}$]{.light-blue} ile çarpılır.
* Temel değişkenlerden [$a_1$]{.red} çözümden çıkarken, [$x_1$]{.red} çözüme girer.
* Anahtar satır, [$-4$]{.light-blue} ile çarpılarak [$a_2$]{.light-blue} ile, [$-1$]{.light-blue} ile çarpılarak [$s_2$]{.light-blue} ile toplanır.
* [$7M-4$]{.green} en büyük değer olduğundan [$x_1$]{.red} [anahtar sütun]{.light-blue} dur.

:::
:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (6)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Satır İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_05_update_base_row.html >}}
```
:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 93%;"}
[Anahtar satır için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 3 \\ 1 \\ 0 \\ 0 \\ 1 \\ 0 \\ 3 \end{pmatrix} \times \frac{1}{3} = \begin{pmatrix} 1 \\ 0.33 \\ 0 \\ 0 \\ 0.33 \\ 0 \\ 1  \end{pmatrix}$$
:::

:::

:::

:::




## Örnek 4: Büyük M Minimizasyon Problemi (7)

::: {.callout-tip icon=false title="Örnek 4: Diğer Satırlar İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_06_update_other_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="35%"}

:::{style="font-size: 65%;"}
[Diğer satırlar için değerlerin hesaplanması $a_2$]{.red}

$$\begin{pmatrix} 4 \\ 3 \\ -1 \\ 0 \\ 0 \\ 1 \\ 6 \end{pmatrix} - 4 \times \begin{pmatrix} 1 \\ 0.33 \\ 0 \\ 0 \\ 0.33 \\ 0 \\ 1  \end{pmatrix} = \begin{pmatrix} 0 \\ 1.67 \\ -1 \\ 0 \\ -1.33 \\ 1 \\ 2 \end{pmatrix} $$

[Diğer satırlar için değerlerin hesaplanması $s_2$]{.red}

$$\begin{pmatrix} 1 \\ 2 \\ 0 \\ 1 \\ 0 \\ 0 \\ 4 \end{pmatrix} - 1 \times \begin{pmatrix} 1 \\ 0.33 \\ 0 \\ 0 \\ 0.33 \\ 0 \\ 1  \end{pmatrix} = \begin{pmatrix} 0 \\ 1.67 \\ 0 \\ 1 \\ -0.33 \\ 0 \\ 3 \end{pmatrix} $$

:::
:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (8)

::: {.callout-tip icon=false title="Örnek 4: Simpleks Adım Sonu (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="84%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter01_07_after_objective.html >}}
```
:::
* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.
:::


::: {.column width="1%"}

:::

::: {.column width="15%"}


* [$2M+4$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}

:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (9)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Satır, Sütun ve Anahtar Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}

:::{.tblbox .tbl-fs-md .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter02_04_select.html >}}
```
:::

* [$1.67M+1.33$]{.green} en büyük değer olduğundan [$x_2$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$1.20$]{.red} olduğundan [$a_2$]{.red} [anahtar satırdır]{.light-blue}.
:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::{style="font-size: 90%;"}
* Anahtar sayı [$1.67$]{.red} olduğundan [$a_2$]{.light-blue} satırı [$1.67$]{.light-blue} ile bölünmelidir.
* Temel değişkenlerden [$a_2$]{.red} çözümden çıkarken, [$x_2$]{.red} çözüme girer.
* Anahtar satır [$-0.33$]{.light-blue} ile çarpılarak [$x_1$]{.light-blue} ile, [$-1.67$]{.light-blue} ile çarpılarak [$s_2$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (10)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Satır İçin Yeni Değerler (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter02_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


[Anahtar satır için değerlerin hesaplanması $a_2$]{.red}

$$\begin{pmatrix} 0 \\ 1.67 \\ -1 \\ 0 \\ -1.33 \\ 1 \\ 2 \end{pmatrix} \div 1.67 = \begin{pmatrix} 0 \\ 1 \\ -0.60 \\ 0 \\ -0.80 \\ 0.60 \\ 1.20 \end{pmatrix}$$
:::

:::

:::

:::



## Örnek 4: Büyük M Minimizasyon Problemi (11)

::: {.callout-tip icon=false title="Örnek 4: Diğer Satırlar İçin Yeni Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter02_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="39%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 1 \\ 0.33 \\ 0 \\ 0 \\ 0.33 \\ 0 \\ 1 \end{pmatrix} - 0.33 \times \begin{pmatrix} 0 \\ 1 \\ -0.60 \\ 0 \\ -0.80 \\ 0.60 \\ 1.20  \end{pmatrix} = \begin{pmatrix} 1 \\ 0 \\ 0.20 \\ 0 \\ 0.60 \\ -0.20 \\ 0.60 \end{pmatrix} $$

[Diğer satırlar için değerlerin hesaplanması $s_2$]{.red}

$$\begin{pmatrix} 0 \\ 1.67 \\ 0 \\ 1 \\ -0.33 \\ 0 \\ 3 \end{pmatrix} - 1.67 \times \begin{pmatrix} 0 \\ 1 \\ -0.60 \\ 0 \\ -0.80 \\ 0.60 \\ 1.20  \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 1 \\ 1 \\ 1 \\ -1 \\ 1 \end{pmatrix} $$

:::
:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (12)

::: {.callout-tip icon=false title="Örnek 4: Simpleks Adım Sonu (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter02_07_after_objective.html >}}
```

:::

* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

* [$3.60$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}
:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (13)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Satır, Sütun ve Anahtar Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter03_04_select.html >}}
```
:::

* [$0.20$]{.green} en büyük değer olduğundan [$s_1$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$1$]{.red} olduğundan [$s_2$]{.red} [anahtar satırdır]{.light-blue}.
:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::{style="font-size: 85%;"}

* Anahtar sayı [$1$]{.red} olduğundan [$s_2$]{.light-blue} satırı aynı kalabilir.
* Temel değişkenlerden [$s_2$]{.red} çözümden çıkarken, [$s_1$]{.red} çözüme girer.
* Anahtar satır [$-0.20$]{.light-blue} ile çarpılarak [$x_1$]{.light-blue} ile, [$0.60$]{.light-blue} ile çarpılarak [$x_2$]{.light-blue} ile toplanır.
:::

:::

:::

:::


## Örnek 4: Büyük M Minimizasyon Problemi (14)

::: {.callout-tip icon=false title="Örnek 4: Anahtar Satır İçin Yeni Değerler (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter03_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


:::

:::

:::

:::

## Örnek 4: Büyük M Minimizasyon Problemi (15)

::: {.callout-tip icon=false title="Örnek 4: Diğer Satırlar İçin Yeni Değer (İter 3)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter03_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="39%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 1 \\ 0 \\ 0.20 \\ 0 \\ 0.60 \\ -0.20 \\ 0.60 \end{pmatrix} - 0.20 \times \begin{pmatrix} 0 \\ 0 \\ 1 \\ 1 \\ 1 \\ -1 \\ 1  \end{pmatrix} = \begin{pmatrix} 1 \\ 0 \\ 0 \\ -0.20 \\ 0.40 \\ 0 \\ 0.40 \end{pmatrix} $$

[Diğer satırlar için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 0 \\ 1 \\ -0.60 \\ 0 \\ -0.80 \\ 0.60 \\ 1.20 \end{pmatrix} + 0.60 \times \begin{pmatrix} 0 \\ 0 \\ 1 \\ 1 \\ 1 \\ -1 \\ 1  \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0.60 \\ -0.20 \\ 0 \\ 1.80 \end{pmatrix} $$

:::
:::

:::

:::



## Örnek 4: Büyük M Minimizasyon Problemi (16)

::: {.callout-tip icon=false title="Örnek 4: Simpleks Adım Sonu (İter 3)" style="font-size: 80%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex4\ex4_iter03_07_after_objective.html >}}
```

:::



:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

:::{style="font-size: 120%;"}
* Son durumda [$Z=3.40$]{.light-blue} amaç fonksiyonu için bulunabilecek en küçük değerdir.
* Bu çözümde [$x_1 = 0.40$]{.light-blue}, [$x_2 =1.80$]{.light-blue}, [$s_1 = 1$]{.light-blue}, [$s_2=0$]{.light-blue}, [$a_1=0$]{.light-blue}  ve [$a_2 = 0$]{.light-blue}’dır.
:::

:::

:::

:::{style="font-size: 120%;"}

* [$z_j-c_j$]{.light-blue} değerlerinin tamamı [$\leq 0$]{.light-blue} olduğundan çözüm optimuma ulaşmıştır.
:::
:::


## Örnek 5: Büyük M Minimizasyon Problemi (1)

::: {.callout-tip icon=false title="Örnek 5: Büyük M Minimizasyon Problemi (1)" style="font-size: 120%;"}

::: columns
::: {.column width="40%"}
Aşağıdaki doğrusal programlama problemini simpleks yöntemle çözünüz.

[$Z_{min}=2x_1+3x_2$]{.light-blue}

[$0.5x_1 + 0.25x_2  \leq 4$]{.light-blue}

[$x_1 + 3x_2 \geq 20$]{.light-blue}

[$x_1 + x_2 = 10$]{.light-blue}


[$x_1$ ,$x_2 \geq 0$]{.light-blue}


:::


::: {.column width="1%"}

:::

::: {.column width="59%"}

:::{.fragment fragment-index=5}
[Standart Form:]{.red}
:::

:::{.fragment fragment-index=6 style="font-size: 100%;"}
\begin{multline}
Z_{min}=2x_1+3x_2 \\ 
 \color{orange}{+0s_1+0s_2}
 \color{green}{+MA_1+MA_2}
\end{multline}
:::


:::{.fragment fragment-index=7 style="font-size: 85%;"}

$$
\begin{alignedat}{7}
0.5x_1 &+& 0.25x_2 &\color{orange}+& {\color{orange} {1s_1 + 0s_2}}{\color{green} {+0A_1 + 0A_2}} &\;\color{orange}= & 4,\\
x_1 &+& 3x_2 &\color{orange}+& {\color{orange} {0s_1 - 1s_2}}{\color{green} {+1A_1 + 0A_2}} &\;\color{orange}= & 20,\\
x_1 &+& x_2 &\color{orange}+& {\color{orange} {0s_1 + 0s_2}}{\color{green} {+0A_1 + 1A_2}} &\;\color{orange}= & 10,
\end{alignedat}
$$

:::

:::{.fragment fragment-index=8 style="font-size: 95%;"}
$x_1$, $x_2 \geq 0$, [$s_1$, $s_2 \geq 0$]{.orange} ve [$A_1$ , $A_2 \geq 0$]{.green} 

:::

:::

:::

:::


## Örnek 5: Büyük M Minimizasyon Problemi (2)

::: {.callout-tip icon=false title="Örnek 5: Başlangıç Tablosu" style="font-size: 100%;"}

::: columns

::: {.column width="73%"}
:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_01_before.html >}}
```
:::


:::




::: {.column width="1%"}

:::

::: {.column width="20%"}
:::

:::
:::

## Örnek 5: Büyük M Minimizasyon Problemi (3)

::: {.callout-tip icon=false title="Örnek 5: $Z_j$ ve $Z_j-C_j$ (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="80%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_02_write.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::


## Örnek 5: Büyük M Minimizasyon Problemi (4)

::: {.callout-tip icon=false title="Örnek 5: Anahtar Sütun (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="79%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_03_enter_col.html >}}
```
:::


:::


::: {.column width="1%"}

:::

::: {.column width="20%"}

:::

:::
:::

## Örnek 5: Büyük M Minimizasyon Problemi (5)

::: {.callout-tip icon=false title="Örnek 5: Anahtar Satır (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_04_select.html >}}
```
:::

:::

::: {.column width="1%"}

:::

::: {.column width="25%"}

:::{style="font-size: 80%;"}
* En düşük oran [$6.67$]{.red} olduğundan [$a_1$]{.red} [anahtar satırdır]{.light-blue}.
* Anahtar sayı [$3$]{.red} olduğundan [$a_1$]{.light-blue} satırı [$\frac{1}{3}$]{.light-blue} ile çarpılır.
* Temel değişkenlerden [$a_1$]{.red} çözümden çıkarken, [$x_2$]{.red} çözüme girer.
* Anahtar satır, [$-\frac{1}{4}$]{.light-blue} ile çarpılarak [$s_1$]{.light-blue} ile, [$-1$]{.light-blue} ile çarpılarak [$a_2$]{.light-blue} ile  toplanır.
* [$4M-3$]{.green} en büyük değer olduğundan [$x_2$]{.red} [anahtar sütun]{.light-blue} dur.

:::

:::

:::

:::


## Örnek 5: Büyük M Minimizasyon Problemi (6)

::: {.callout-tip icon=false title="Örnek 5: Anahtar Satır İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_05_update_base_row.html >}}
```
:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 93%;"}
[Anahtar satır için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 1 \\ 3 \\ 0 \\ -1 \\ 1 \\ 0 \\ 20 \end{pmatrix} \times \frac{1}{3} = \begin{pmatrix} 0.33 \\ 1 \\ 0 \\ -0.33 \\ 0.33 \\ 0\\ 6.67 \end{pmatrix}$$
:::

:::

:::

:::




## Örnek 5: Büyük M Minimizasyon Problemi (7)

::: {.callout-tip icon=false title="Örnek 5: Diğer Satırlar İçin Yeni Değer (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="60%"}


:::{.tblbox .tbl-fs-xl .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_06_update_other_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="38%"}

:::{style="font-size: 70%;"}
[Diğer satırlar için değerlerin hesaplanması $s_1$]{.red}

$$\begin{pmatrix} 0.50 \\ 0.25 \\ 1 \\ 0 \\ 0 \\ 0 \\ 4 \end{pmatrix} - \frac{1}{4} \times \begin{pmatrix} 0.33 \\ 1 \\ 0 \\ -0.33 \\ 0.33 \\ 0\\ 6.67 \end{pmatrix}= \begin{pmatrix} 0.42 \\ 0 \\ 1 \\ 0.08 \\ -0.08 \\ 0 \\ 2.33 \end{pmatrix} $$
[Diğer satırlar için değerlerin hesaplanması $a_2$]{.red}

$$\begin{pmatrix} 1 \\ 1 \\ 0 \\ 0 \\ 0 \\ 1 \\ 10 \end{pmatrix} - 1 \times \begin{pmatrix} 0.33 \\ 1 \\ 0 \\ -0.33 \\ 0.33 \\ 0\\ 6.67 \end{pmatrix}= \begin{pmatrix} 0.67 \\ 0 \\ 0 \\ 0.33 \\ -0.33 \\ 1 \\ 3.33 \end{pmatrix} $$
:::
:::

:::

:::


## Örnek 5: Büyük M Minimizasyon Problemi (8)

::: {.callout-tip icon=false title="Örnek 5: Simpleks Adım Sonu (İter 1)" style="font-size: 100%;"}

::: columns
::: {.column width="84%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter01_07_after_objective.html >}}
```
:::
* [$Z_j - C_j$]{.light-blue} değerlerinde [$\geq 0$]{.light-blue} değerler olduğu için henüz optimuma ulaşılmadı.
:::


::: {.column width="1%"}

:::

::: {.column width="15%"}

:::{style="font-size: 90%;"}
* [$3.33M+20$]{.light-blue} optimum değer değil.
* [İterasyona devam edilmeli.]{.orange}
:::
:::

:::

:::


## Örnek 5: Büyük M Minimizasyon Problemi (9)

::: {.callout-tip icon=false title="Örnek 5: Anahtar Satır, Sütun ve Anahtar Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="70%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter02_04_select.html >}}
```
:::

* [$0.67M+1$]{.red} en büyük değer olduğundan [$x_1$]{.red} [anahtar sütun]{.light-blue}, en düşük oran [$5$]{.red} olduğundan [$a_2$]{.red} [anahtar satırdır]{.light-blue}.
:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

* Anahtar sayı [$0.67$]{.red} olduğundan [$a_2$]{.light-blue} satırı [$\frac{3}{2}$]{.light-blue} ile çarpılmalıdır.
* Temel değişkenlerden [$a_2$]{.red} çözümden çıkarken, [$x_1$]{.red} çözüme girer.
* Anahtar satır, [$-0.42$]{.light-blue} ile çarpılarak [$s_1$]{.light-blue} ile, [$-0.33$]{.light-blue} ile çarpılarak [$x_2$]{.light-blue} ile toplanır.

:::

:::

:::


## Örnek 5: Büyük M Minimizasyon Problemi (10)

::: {.callout-tip icon=false title="Örnek 5: Anahtar Satır İçin Yeni Değerler (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="68%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter02_05_update_base_row.html >}}
```
:::

:::


::: {.column width="2%"}

:::

::: {.column width="30%"}


:::{style="font-size: 75%;"}


[Anahtar satır için değerlerin hesaplanması $x_1$]{.red}

$$\begin{pmatrix} 0.67 \\ 0 \\ 0 \\ 0.33 \\ -0.33 \\ 1 \\ 3.33  \end{pmatrix} \times \frac{3}{2} = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0.5 \\ -0.5 \\ 1.5 \\ 5 \end{pmatrix}$$
:::

:::

:::

:::



## Örnek 5: Büyük M Minimizasyon Problemi (11)

::: {.callout-tip icon=false title="Örnek 5: Diğer Satırlar İçin Yeni Değer (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="63%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter02_06_update_other_row.html >}}
```

:::

:::


::: {.column width="1%"}

:::

::: {.column width="35%"}

:::{style="font-size: 65%;"}
[Diğer satırlar için değerlerin hesaplanması $s_1$]{.red}

$$\begin{pmatrix} 0.42 \\ 0 \\ 1 \\ 0.08 \\ -0.08 \\ 0 \\ 2.33 \end{pmatrix} - 0.42 \times \begin{pmatrix} 1 \\ 0 \\ 0\\ 0.50 \\ -0.50\\ 1.5 \\ 5 \end{pmatrix}= \begin{pmatrix} 0 \\ 0 \\ 1 \\ -0.12 \\ 0.12 \\ -0.62 \\ 0.25 \end{pmatrix} $$
[Diğer satırlar için değerlerin hesaplanması $x_2$]{.red}

$$\begin{pmatrix} 0.33 \\ 1 \\ 0 \\ -0.33 \\ 0.33 \\ 0 \\ 6.67 \end{pmatrix} - 0.33 \times \begin{pmatrix} 1 \\ 0 \\ 0\\ 0.50 \\ -0.50\\ 1.5 \\ 5 \end{pmatrix}= \begin{pmatrix} 0 \\ 1 \\ 0 \\ -0.50 \\ 0.50 \\ -0.50 \\ 5 \end{pmatrix} $$
:::
:::

:::

:::


## Örnek 5: Büyük M Minimizasyon Problemi (12)

::: {.callout-tip icon=false title="Örnek 5: Simpleks Adım Sonu (İter 2)" style="font-size: 100%;"}

::: columns
::: {.column width="73%"}

:::{.tblbox .tbl-fs-lg .w-100  .pad-none .text-center .scroll-x .scroll-y}
```{=html}
{{< include .\out\ex5\ex5_iter02_07_after_objective.html >}}
```

:::

* [$Z_j - C_j$]{.light-blue} değerlerinin tamamı [$\leq 0$]{.light-blue} olduğundan çözüm optimuma ulaşmıştır.

:::


::: {.column width="1%"}

:::

::: {.column width="25%"}

* Son durumda [$Z = 25$]{.light-blue} amaç fonksiyonu için bulunabilecek en küçük değerdir.
* Bu çözümde [$x_1 = 5$]{.light-blue}, [$x_2 =5$]{.light-blue}, [$s_1 =0.25$]{.light-blue}, [$s_2 = 0$]{.light-blue}, [$a_1=0$]{.light-blue}  ve [$a_2 = 0$]{.light-blue}’dır.
:::

:::

:::
